[package]
name = "day18"
version = "0.1.0"
authors = ["≈Åukasz Konopka <lukasz.konopka@tooploox.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-segmentation = "1.7.1"
nom = "6.0.1"
